name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Updated to use Node.js 23.6

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Ensure your build script is correct

    - name: Deploy to GitHub Pages
      uses: SidekickFM/SidekickFE/actions-gh-pages@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Change this to your build output directory 